name: google_maps_place_picker_validation
description: Place picker and Shape picker on Google Maps for Flutter
version: 2.0.2
homepage: https://github.com/masreplay/google_maps_place_picker_validation
publish_to: none
environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.10.5 <4.0.0"

dependencies:
  flutter_lints: ^2.0.1

  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  google_api_headers: ^4.1.1
  google_maps_flutter: ^2.6.1
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.2.1
  # location: ^4.4.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.3.3
  map_utils:
    git: https://github.com/masreplay/map_utils.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   web: ^0.5.1

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
